version: '3'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=url_shortener
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
  redis:
    image: redis:latest

  memcache:
    build: ./memcache
    ports:
      - "8081:8081"
    depends_on:
      - redis

  shortener:
    build: ./shortener
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  db:
    driver: local
